runtime: nodejs22
instance_class: F1

env_variables:
  INSTANCE_CONNECTION_NAME: "project-damarq2ccos4:asia-southeast2:damardata"
  DB_USER: "damarROOT"
  DB_PASSWORD: "pP|.[TfQJ.enG=)Y"
  DB_NAME: "Q2_ProjectCCO"
  DB_SOCKET_PATH: "/cloudsql/project-damarq2ccos4:asia-southeast2:damardata"
  JWT_SECRET: "your_jwt_secret_key_change_this_in_production"

beta_settings:
  cloud_sql_instances: project-damarq2ccos4:asia-southeast2:damardata

handlers:
  - url: /.*
    script: auto